Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\ProgramData\miniconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\miniconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\miniconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\miniconda3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\ProgramData\miniconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\miniconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\ProgramData\miniconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Lectura de datos y exploraci√≥n inicial de la base
options(warn=-1)
library(foreign)
Panel <- read.dta("http://dss.princeton.edu/training/Panel101.dta") # Source: http://dss.princeton.edu/training, 
View(head(Panel,10))

------------------

Error in download.file(file, tmp, quiet = TRUE, mode = "wb"): no fue posible abrir la URL 'http://dss.princeton.edu/training/Panel101.dta'
Traceback:

1. read.dta("http://dss.princeton.edu/training/Panel101.dta")
2. download.file(file, tmp, quiet = TRUE, mode = "wb")
ERROR: Error in download.file(file, tmp, quiet = TRUE, mode = "wb"): no fue posible abrir la URL 'http://dss.princeton.edu/training/Panel101.dta'


